import { causten, core_sans } from "@/utils/fonts";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${causten.variable} ${core_sans.variable}`}>
        {children}
      </body>
    </html>
  );
}
